language: java
jdk:
  - oraclejdk8
os:
  - linux
before_install:
 - cd utils_dev
jobs:
  include:
    - stage: Main Build
      script: ant build
    - stage: Notification
      notifications:
      email:
        recipients:
          - ysenih@erpya.com
          - info@erpya.com
      on_success: always # default: change
      on_failure: always # default: always