language: java
jdk:
- oraclejdk8
os:
- linux
dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_1d0a162d6238_key -iv $encrypted_1d0a162d6238_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- ssh-keyscan -t rsa $REMOTE_HOST > $HOME/.ssh/known_hosts
- echo -e "Host $REMOTE_HOST\n\tStrictHostKeyChecking no" >> ~/.ssh/config
- echo " IdentityFile /home/travis/build/erpcya/adempiere/deploy_rsa" >> ~/.ssh/config;
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

- cd utils_dev
jobs:- ls
  include:
  - stage: Main Build Test
    script: ant build
before_deploy:
- git config --local user.name "YamelSenih"
- git config --local user.email "yamelsenih@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$access_key_id"
  file:
  - install/build/Adempiere_390LTS.tar.gz
  - install/build/Adempiere_390LTS.tar.gz.MD5
  - install/build/Adempiere_390LTS.zip
  - install/build/Adempiere_390LTS.zip.MD5
  on:
    tags: true
  skip_cleanup: true
branches:
  only:
  - hotfix/#1592-hotfix-Commission
notifications:
  email:
    recipients:
    - ysenih@erpya.com
    - info@erpya.com
    on_success: always
    on_failure: always
after_success:
- cd ..
- chmod +x deploy.sh
- sh deploy.sh
