language: java
jdk:
- oraclejdk8
os:
- linux
before_install:
- openssl aes-256-cbc -K $encrypted_1d0a162d6238_key -iv $encrypted_1d0a162d6238_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- cd utils_dev
jobs:
  include:
  - stage: Main Build Test
    script: ant build
before_deploy:
- git config --local user.name "YamelSenih"
- git config --local user.email "yamelsenih@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$access_key_id"
  file:
  - install/build/Adempiere_390LTS.tar.gz
  - install/build/Adempiere_390LTS.tar.gz.MD5
  - install/build/Adempiere_390LTS.zip
  - install/build/Adempiere_390LTS.zip.MD5
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
notifications:
  email:
    recipients:
    - ysenih@erpya.com
    - info@erpya.com
    on_success: always
    on_failure: always
addons:
  ssh_known_hosts:
  - "$REMOTE_HOST"
after_success:
- cd ..
- "./deploy.sh"
