language: java
install: ant deps
echo Cleanup ...
java -Xms128m -Xmx512m -classpath ../tools/lib/ant.jar:../tools/lib/ant-launcher.jar:../tools/lib/ant-swing.jar:../tools/lib/ant-commons-net.jar:../tools/lib/commons-net.jar  org.apache.tools.ant.Main clean
echo Finish ...