language: java
jdk:
- openjdk8
os:
- linux
sudo: required
addons:
  apt:
    packages:
      ant
jobs:
  include:
  - stage: Main Build Test
    script: ant build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: "/home/travis/build/erpcya/adempiere/adempiere/install/Adempiere_392LTS.tar.gz"
  skip_cleanup: true
  on:
    tags: true