language: java
jdk:
- openjdk8
os:
- linux
sudo: required
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
before_install:
  - echo "utils_dev";
  - echo "Test";
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11 
  - sleep 1
jobs:
  include:
  - stage: Main Build Test
    script: ant build
