language: java
jdk:
  - oraclejdk8
os:
  - linux
before_install:
 - cd utils_dev
jobs:
  include:
    - stage: Main Build
      script: ant build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YamelSenih"
  - git config --local user.email "yamelsenih@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
      provider: releases
      api_key: "$access_key_id"
      file: 
        - "install/build/Adempiere_390LTS.tar.gz"
        - "install/build/Adempiere_390LTS.tar.gz.MD5"
        - "install/build/Adempiere_390LTS.zip"
        - "install/build/Adempiere_390LTS.zip.MD5"
      on:
        tags: true
        only:
          - develop
          - master 
          - hotfix/#1592-hotfix-Commission
      skip_cleanup: true
notifications:
  email:
    recipients:
      - ysenih@erpya.com
      - info@erpya.com
    on_success: always # default: change
    on_failure: always # default: always