# This is a basic workflow to help you get started with Actions

name: ADempiere Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - '!develop-1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Build ADempiere with ant
      - name: Build Adempiere ...
        run: |
           echo $GITHUB_REF
           echo $GITHUB_HEAD_REF
           echo $GITHUB_BASE_REF
           echo ${{ github.ref }}
           cd utils_dev
           ant complete
